"""Laplacian mesh smoothing filters (Warp)."""

from __future__ import annotations

import warp as wp
import warp.optim.linear as wpl
import warp.sparse as wps

import triwarp as tw
from triwarp import laplacian
from triwarp.constants import TILE_1D
from triwarp.kernels import array as kernel_array
from triwarp.kernels import laplacian as kernel_laplacian
from triwarp.kernels import reduce as kernel_reduce
from triwarp.kernels import smoothing as kernel_smoothing
from triwarp.triangles import face_normals_and_areas
from triwarp.vertices import mean_vertex_normals

_CG_TOLERANCE = 1e-10


def _to_vec3d(vertices: wp.array[wp.vec3]) -> wp.array[wp.vec3d]:
    out = wp.empty(int(vertices.shape[0]), dtype=wp.vec3d, device=vertices.device)
    wp.map(kernel_array.to_vec3d, vertices, out=out)
    return out


def _to_vec3(positions: wp.array[wp.vec3d]) -> wp.array[wp.vec3]:
    out = wp.empty(int(positions.shape[0]), dtype=wp.vec3, device=positions.device)
    wp.map(kernel_array.to_vec3, positions, out=out)
    return out


def _apply_operator(
    operator: wps.BsrMatrix[wp.float32], v_in: wp.array[wp.vec3d], out_lv: wp.array[wp.vec3d]
) -> None:
    wp.launch(
        kernel_laplacian.apply_operator,
        dim=int(v_in.shape[0]),
        inputs=[operator.offsets, operator.columns, operator.values, v_in, out_lv],
        device=v_in.device,
    )


def _mesh_volume(positions: wp.array[wp.vec3d], faces: wp.array[wp.int32]) -> float:
    n_faces = int(faces.shape[0]) // 3
    device = positions.device
    volumes = wp.empty(n_faces, dtype=wp.float64, device=device)
    wp.launch(
        kernel_smoothing.signed_tet_volumes,
        dim=n_faces,
        inputs=[positions, faces, volumes],
        device=device,
    )
    # Device-side tiled sum: only the 8-byte total crosses to the host, not the whole array.
    total = wp.zeros(1, dtype=wp.float64, device=device)
    n_tiles = (n_faces + TILE_1D - 1) // TILE_1D
    wp.launch_tiled(
        kernel_reduce.sum1d_tiled,
        dim=[n_tiles],
        inputs=[volumes, total],
        block_dim=TILE_1D,
        device=device,
    )
    return float(total.numpy()[0])


def _apply_volume_constraint(
    positions: wp.array[wp.vec3d], faces: wp.array[wp.int32], vol_ini: float
) -> None:
    vol_new = _mesh_volume(positions, faces)
    if vol_new != 0.0:
        factor = (vol_ini / vol_new) ** (1.0 / 3.0)
        wp.map(wp.mul, positions, wp.float64(factor), out=positions)


def _require_cuda(device: wp.DeviceLike, name: str) -> None:
    if wp.get_device(device).is_cpu:
        raise NotImplementedError(
            f"{name} requires a CUDA device: warp.optim.linear.cg produces NaN on the CPU "
            "device in Warp 1.14-1.15."
        )


def filter_laplacian(
    vertices: wp.array[wp.vec3],
    faces: wp.array[wp.int32],
    lamb: float = 0.5,
    iterations: int = 10,
    implicit_time_integration: bool = False,
    volume_constraint: bool = True,
    laplacian_operator: wps.BsrMatrix[wp.float32] | None = None,
) -> wp.array[wp.vec3]:
    """
    Laplacian mesh smoothing (Vollmer et al.; Desbrun et al. implicit fairing).

    Diffuses each vertex toward the mean of its 1-ring neighbors. With ``implicit_time_integration``
    the diffusion is solved implicitly (backward Euler, unconditionally stable); otherwise an
    explicit forward-Euler step is used (stable for ``lamb <= 1``). Mirrors
    [`trimesh.smoothing.filter_laplacian`][] but returns a new vertex array instead of mutating
    the mesh in place.

    Parameters
    ----------
    vertices
        ``(n_vertices,)`` mesh vertex positions.
    faces
        Length-``3 * n_faces`` ``wp.int32`` triangle index buffer.
    lamb
        Diffusion speed. ``0`` leaves the mesh unchanged; larger values smooth faster.
    iterations
        Number of smoothing passes.
    implicit_time_integration
        If ``True`` solve ``((1 + lamb) I - lamb L) V' = V`` each pass via conjugate gradient
        (**CUDA only** — raises on CPU). If ``False`` apply the explicit step
        ``V' = V + lamb (L V - V)``.
    volume_constraint
        If ``True`` rescale the mesh after each pass to preserve its initial volume, counteracting
        Laplacian shrinkage.
    laplacian_operator
        Optional precomputed row-stochastic operator (see
        [`laplacian`][triwarp.laplacian.laplacian]). Autogenerated (uniform weights) when ``None``.

    Returns
    -------
    wp.array[wp.vec3]
        Smoothed ``(n_vertices,)`` vertex positions on ``vertices.device``.

    See Also
    --------
    [`filter_taubin`][triwarp.smoothing.filter_taubin]
    [`filter_humphrey`][triwarp.smoothing.filter_humphrey]
    [`filter_implicit_fairing`][triwarp.smoothing.filter_implicit_fairing]
    [`trimesh.smoothing.filter_laplacian`][]
    """
    device = vertices.device
    n = int(vertices.shape[0])
    if n == 0 or iterations == 0:
        out = wp.empty(n, dtype=wp.vec3, device=device)
        wp.copy(out, vertices)
        return out

    operator = (
        laplacian_operator
        if laplacian_operator is not None
        else laplacian.laplacian(vertices, faces)
    )
    positions = _to_vec3d(vertices)
    vol_ini = _mesh_volume(positions, faces) if volume_constraint else 0.0

    if implicit_time_integration:
        _require_cuda(device, "filter_laplacian(implicit_time_integration=True)")
        system = _build_implicit_system(operator, lamb, n, device)
        precond = wpl.preconditioner(system, "diag")
        components = _empty_components(n, device)
        solutions = _empty_components(n, device)
        for _ in range(iterations):
            wp.map(kernel_smoothing.extract_components, positions, out=list(components))
            for rhs, solution in zip(components, solutions, strict=True):
                wp.copy(solution, rhs)
                wpl.cg(system, rhs, solution, tol=_CG_TOLERANCE, maxiter=10 * n, M=precond)
            wp.map(kernel_smoothing.combine_components, *solutions, out=positions)
            if volume_constraint:
                _apply_volume_constraint(positions, faces, vol_ini)
    else:
        lv = wp.empty(n, dtype=wp.vec3d, device=device)
        nxt = wp.empty(n, dtype=wp.vec3d, device=device)
        coeff = wp.float64(lamb)
        step = wp.map(
            kernel_smoothing.laplacian_step, positions, lv, coeff, out=nxt, return_kernel=True
        )
        for _ in range(iterations):
            _apply_operator(operator, positions, lv)
            wp.launch(step, dim=n, inputs=[positions, lv, coeff], outputs=[nxt], device=device)
            positions, nxt = nxt, positions
            if volume_constraint:
                _apply_volume_constraint(positions, faces, vol_ini)

    return _to_vec3(positions)


def filter_humphrey(
    vertices: wp.array[wp.vec3],
    faces: wp.array[wp.int32],
    alpha: float = 0.1,
    beta: float = 0.5,
    iterations: int = 10,
    laplacian_operator: wps.BsrMatrix[wp.float32] | None = None,
) -> wp.array[wp.vec3]:
    """
    Laplacian smoothing with Humphrey (HC) filtering (Vollmer et al.).

    Each pass performs a Laplacian smoothing step and then pushes the vertices partway back
    toward their original and pre-smoothing positions, strongly reducing the shrinkage of plain
    Laplacian smoothing. Mirrors [`trimesh.smoothing.filter_humphrey`][].

    Parameters
    ----------
    vertices
        ``(n_vertices,)`` mesh vertex positions.
    faces
        Length-``3 * n_faces`` ``wp.int32`` triangle index buffer.
    alpha
        Shrinkage control in ``[0, 1]``: ``0`` ignores the original positions, ``1`` disables
        smoothing.
    beta
        Correction aggressiveness in ``[0, 1]``: ``0`` disables smoothing, ``1`` is most aggressive.
    iterations
        Number of smoothing passes.
    laplacian_operator
        Optional precomputed row-stochastic operator (see
        [`laplacian`][triwarp.laplacian.laplacian]). Autogenerated (uniform weights) when ``None``.

    Returns
    -------
    wp.array[wp.vec3]
        Smoothed ``(n_vertices,)`` vertex positions on ``vertices.device``.

    See Also
    --------
    [`filter_laplacian`][triwarp.smoothing.filter_laplacian]
    [`trimesh.smoothing.filter_humphrey`][]
    """
    device = vertices.device
    n = int(vertices.shape[0])
    if n == 0 or iterations == 0:
        out = wp.empty(n, dtype=wp.vec3, device=device)
        wp.copy(out, vertices)
        return out

    operator = (
        laplacian_operator
        if laplacian_operator is not None
        else laplacian.laplacian(vertices, faces)
    )
    positions = _to_vec3d(vertices)
    original = wp.empty(n, dtype=wp.vec3d, device=device)
    wp.copy(original, positions)

    lv = wp.empty(n, dtype=wp.vec3d, device=device)
    b = wp.empty(n, dtype=wp.vec3d, device=device)
    lb = wp.empty(n, dtype=wp.vec3d, device=device)
    nxt = wp.empty(n, dtype=wp.vec3d, device=device)
    alpha64 = wp.float64(alpha)
    beta64 = wp.float64(beta)
    residual = wp.map(
        kernel_smoothing.humphrey_residual,
        lv,
        original,
        positions,
        alpha64,
        out=b,
        return_kernel=True,
    )
    update = wp.map(
        kernel_smoothing.humphrey_update, lv, b, lb, beta64, out=nxt, return_kernel=True
    )
    for _ in range(iterations):
        # ``positions`` doubles as the previous-iterate ``q`` (it is only read this pass).
        _apply_operator(operator, positions, lv)
        wp.launch(
            residual, dim=n, inputs=[lv, original, positions, alpha64], outputs=[b], device=device
        )
        _apply_operator(operator, b, lb)
        wp.launch(update, dim=n, inputs=[lv, b, lb, beta64], outputs=[nxt], device=device)
        positions, nxt = nxt, positions

    return _to_vec3(positions)


def filter_taubin(
    vertices: wp.array[wp.vec3],
    faces: wp.array[wp.int32],
    lamb: float = 0.5,
    nu: float = 0.5,
    iterations: int = 10,
    laplacian_operator: wps.BsrMatrix[wp.float32] | None = None,
) -> wp.array[wp.vec3]:
    """
    Taubin lambda/nu mesh smoothing (Vollmer et al.).

    Alternates a shrinking diffusion step (``+lamb``) on even passes with an inflating step
    (``-nu``) on odd passes, so the low-frequency shape is preserved while high-frequency noise is
    removed with little volume loss. Mirrors [`trimesh.smoothing.filter_taubin`][].

    Parameters
    ----------
    vertices
        ``(n_vertices,)`` mesh vertex positions.
    faces
        Length-``3 * n_faces`` ``wp.int32`` triangle index buffer.
    lamb
        Shrinking step size in ``[0, 1]``.
    nu
        Inflating step size in ``[0, 1]``; typically chosen so ``0 < 1/lamb - 1/nu < 0.1``.
    iterations
        Number of smoothing passes (shrink and inflate alternate by pass index).
    laplacian_operator
        Optional precomputed row-stochastic operator (see
        [`laplacian`][triwarp.laplacian.laplacian]). Autogenerated (uniform weights) when ``None``.

    Returns
    -------
    wp.array[wp.vec3]
        Smoothed ``(n_vertices,)`` vertex positions on ``vertices.device``.

    See Also
    --------
    [`filter_laplacian`][triwarp.smoothing.filter_laplacian]
    [`trimesh.smoothing.filter_taubin`][]
    """
    device = vertices.device
    n = int(vertices.shape[0])
    if n == 0 or iterations == 0:
        out = wp.empty(n, dtype=wp.vec3, device=device)
        wp.copy(out, vertices)
        return out

    operator = (
        laplacian_operator
        if laplacian_operator is not None
        else laplacian.laplacian(vertices, faces)
    )
    positions = _to_vec3d(vertices)
    lv = wp.empty(n, dtype=wp.vec3d, device=device)
    nxt = wp.empty(n, dtype=wp.vec3d, device=device)
    step = wp.map(
        kernel_smoothing.laplacian_step,
        positions,
        lv,
        wp.float64(lamb),
        out=nxt,
        return_kernel=True,
    )
    for index in range(iterations):
        _apply_operator(operator, positions, lv)
        coeff = lamb if index % 2 == 0 else -nu
        wp.launch(
            step, dim=n, inputs=[positions, lv, wp.float64(coeff)], outputs=[nxt], device=device
        )
        positions, nxt = nxt, positions

    return _to_vec3(positions)


def filter_neighborhood_average(
    vertices: wp.array[wp.vec3],
    faces: wp.array[wp.int32],
    iterations: int = 10,
    laplacian_operator: wps.BsrMatrix[wp.float32] | None = None,
) -> wp.array[wp.vec3]:
    """
    Uniform neighborhood-average smoothing over the closed 1-ring.

    Each pass replaces every vertex by the equal-weight average of itself and its direct
    neighbors, ``v' = (v + sum(v_neighbors)) / (1 + degree)``. Unlike
    [`filter_laplacian`][triwarp.smoothing.filter_laplacian] (which averages the open 1-ring,
    excluding the vertex, and scales the result by ``lamb``) this is the simplest possible
    smoother, with no diffusion coefficient. It is the CPU/GPU-portable analogue of Open3D's
    ``TriangleMesh.filter_smooth_simple``.

    Isolated vertices (degree 0) are left unchanged.

    Parameters
    ----------
    vertices
        ``(n_vertices,)`` mesh vertex positions.
    faces
        Length-``3 * n_faces`` ``wp.int32`` triangle index buffer.
    iterations
        Number of smoothing passes.
    laplacian_operator
        Optional precomputed row-stochastic operator (see
        [`laplacian`][triwarp.laplacian.laplacian]). Autogenerated (uniform weights) when ``None``.

    Returns
    -------
    wp.array[wp.vec3]
        Smoothed ``(n_vertices,)`` vertex positions on ``vertices.device``.

    See Also
    --------
    [`filter_laplacian`][triwarp.smoothing.filter_laplacian]
    [`filter_taubin`][triwarp.smoothing.filter_taubin]
    """
    device = vertices.device
    n = int(vertices.shape[0])
    if n == 0 or iterations == 0:
        out = wp.empty(n, dtype=wp.vec3, device=device)
        wp.copy(out, vertices)
        return out

    # Symmetric adjacency (undirected 1-ring) so boundary vertices average over all their
    # neighbors, matching Open3D's ``adjacency_list``; the directed default is asymmetric there.
    operator = (
        laplacian_operator
        if laplacian_operator is not None
        else laplacian.laplacian(vertices, faces, symmetric=True)
    )
    positions = _to_vec3d(vertices)
    lv = wp.empty(n, dtype=wp.vec3d, device=device)
    nxt = wp.empty(n, dtype=wp.vec3d, device=device)
    # CSR row bounds as aligned per-vertex inputs: degree(i) = offsets[i + 1] - offsets[i].
    starts = operator.offsets[:-1]
    ends = operator.offsets[1:]
    step = wp.map(
        kernel_smoothing.neighborhood_average,
        positions,
        lv,
        starts,
        ends,
        out=nxt,
        return_kernel=True,
    )
    for _ in range(iterations):
        _apply_operator(operator, positions, lv)
        wp.launch(step, dim=n, inputs=[positions, lv, starts, ends], outputs=[nxt], device=device)
        positions, nxt = nxt, positions

    return _to_vec3(positions)


def filter_mut_dif_laplacian(
    vertices: wp.array[wp.vec3],
    faces: wp.array[wp.int32],
    lamb: float = 0.5,
    iterations: int = 10,
    volume_constraint: bool = True,
    laplacian_operator: wps.BsrMatrix[wp.float32] | None = None,
) -> wp.array[wp.vec3]:
    """
    Laplacian smoothing with a mutable diffusion coefficient (Barroqueiro et al.).

    Each pass runs a Laplacian diffusion step whose speed is adapted **per vertex**: the
    coefficient ``lamber`` is scaled by how much of the vertex's Laplacian residual lies along
    its normal, so flat regions diffuse quickly while feature regions diffuse slowly. When
    ``volume_constraint`` is set, the mesh is inflated along its vertex normals (rather than
    isotropically rescaled) to counteract shrinkage. Mirrors
    [`trimesh.smoothing.filter_mut_dif_laplacian`][] but returns a new vertex array instead of
    mutating the mesh in place.

    Following the reference, the vertex normals (and the finite-difference step ``eps``) are
    computed once from the input mesh and held constant across all passes.

    Parameters
    ----------
    vertices
        ``(n_vertices,)`` mesh vertex positions.
    faces
        Length-``3 * n_faces`` ``wp.int32`` triangle index buffer.
    lamb
        Diffusion speed. ``0`` leaves the mesh unchanged; larger values smooth faster.
    iterations
        Number of smoothing passes.
    volume_constraint
        If ``True`` inflate the mesh along its vertex normals after each pass to preserve its
        initial volume (meaningful only for watertight meshes).
    laplacian_operator
        Optional precomputed row-stochastic operator (see
        [`laplacian`][triwarp.laplacian.laplacian]). Autogenerated (uniform weights) when ``None``.

    Returns
    -------
    wp.array[wp.vec3]
        Smoothed ``(n_vertices,)`` vertex positions on ``vertices.device``.

    See Also
    --------
    [`filter_laplacian`][triwarp.smoothing.filter_laplacian]
    [`filter_humphrey`][triwarp.smoothing.filter_humphrey]
    [`filter_taubin`][triwarp.smoothing.filter_taubin]
    [`trimesh.smoothing.filter_mut_dif_laplacian`][]
    """
    device = vertices.device
    n = int(vertices.shape[0])
    if n == 0 or iterations == 0:
        out = wp.empty(n, dtype=wp.vec3, device=device)
        wp.copy(out, vertices)
        return out

    operator = (
        laplacian_operator
        if laplacian_operator is not None
        else laplacian.laplacian(vertices, faces)
    )
    positions = _to_vec3d(vertices)

    # Vertex normals and eps are computed once from the input mesh and reused every pass, matching
    # the trimesh reference (which reads normals off the un-mutated mesh inside its loop).
    face_normals, areas = face_normals_and_areas(vertices, faces)
    normals = mean_vertex_normals(n, faces, face_normals)
    vol_ini = _mesh_volume(positions, faces) if volume_constraint else 0.0
    eps = 0.01 * float(tw.reduce.max(areas)) ** 0.5 if volume_constraint else 0.0

    lv = wp.empty(n, dtype=wp.vec3d, device=device)
    adil = wp.empty(n, dtype=wp.float64, device=device)
    adil_sum = wp.zeros(1, dtype=wp.float64, device=device)
    nxt = wp.empty(n, dtype=wp.vec3d, device=device)
    probe = wp.empty(n, dtype=wp.vec3d, device=device) if volume_constraint else None
    slope = 0.0
    inv_n = wp.float64(1.0 / n)
    n_tiles = (n + TILE_1D - 1) // TILE_1D
    adil_kernel = wp.map(
        kernel_smoothing.mut_dif_adil, normals, positions, lv, out=adil, return_kernel=True
    )
    for index in range(iterations):
        # The mean diffusion coefficient is reduced on device and consumed by the step kernel
        # directly, so the loop body issues no host synchronisation.
        _apply_operator(operator, positions, lv)
        wp.launch(
            adil_kernel, dim=n, inputs=[normals, positions, lv], outputs=[adil], device=device
        )
        adil_sum.zero_()
        wp.launch_tiled(
            kernel_reduce.sum1d_tiled,
            dim=[n_tiles],
            inputs=[adil, adil_sum],
            block_dim=TILE_1D,
            device=device,
        )
        wp.launch(
            kernel_smoothing.mut_dif_step_scaled,
            dim=n,
            inputs=[positions, lv, adil, adil_sum, inv_n, wp.float64(lamb)],
            outputs=[nxt],
            device=device,
        )
        positions, nxt = nxt, positions
        if volume_constraint:
            vol = _mesh_volume(positions, faces)
            if index == 0:
                wp.map(
                    kernel_smoothing.add_scaled_normal,
                    positions,
                    normals,
                    wp.float64(eps),
                    out=probe,
                )
                vol2 = _mesh_volume(probe, faces)
                slope = eps / (vol2 - vol) if vol2 != vol else 0.0
            wp.map(
                kernel_smoothing.add_scaled_normal,
                positions,
                normals,
                wp.float64(slope * (vol_ini - vol)),
                out=positions,
            )

    return _to_vec3(positions)


def filter_implicit_fairing(
    vertices: wp.array[wp.vec3], faces: wp.array[wp.int32], lamb: float = 0.1, iterations: int = 10
) -> wp.array[wp.vec3]:
    """
    Implicit fairing with the cotangent Laplace-Beltrami operator (Desbrun et al.).

    Solves the backward-Euler diffusion ``(M - lamb L) V' = M V`` each pass, where ``L`` is the
    cotangent stiffness matrix ([`cotmatrix`][triwarp.laplacian.cotmatrix]) and ``M`` the
    barycentric lumped mass matrix ([`mass_matrix`][triwarp.laplacian.mass_matrix]), both recomputed
    from the current geometry. This is the most accurate of the smoothing filters (curvature flow;
    libigl tutorial 205, MeshLib ``Laplacian`` in cotangent mode) and is **CUDA only** (raises on
    CPU). The solve uses ``float64`` throughout.

    Intended for closed (watertight) meshes. On meshes with an open boundary the unconstrained
    flow shrinks and degrades the boundary triangles; because the linear system is solved by
    conjugate gradient (the only Warp solver available), repeated passes on such meshes may
    diverge.

    Parameters
    ----------
    vertices
        ``(n_vertices,)`` mesh vertex positions.
    faces
        Length-``3 * n_faces`` ``wp.int32`` triangle index buffer.
    lamb
        Diffusion time step. Larger values smooth faster; the implicit solve is unconditionally
        stable.
    iterations
        Number of smoothing passes.

    Returns
    -------
    wp.array[wp.vec3]
        Smoothed ``(n_vertices,)`` vertex positions on ``vertices.device``.

    See Also
    --------
    [`filter_laplacian`][triwarp.smoothing.filter_laplacian]
    [`cotmatrix`][triwarp.laplacian.cotmatrix]
    [`mass_matrix`][triwarp.laplacian.mass_matrix]
    """
    device = vertices.device
    n = int(vertices.shape[0])
    n_faces = int(faces.shape[0]) // 3
    if n == 0 or n_faces == 0 or iterations == 0:
        out = wp.empty(n, dtype=wp.vec3, device=device)
        wp.copy(out, vertices)
        return out

    _require_cuda(device, "filter_implicit_fairing")
    positions = _to_vec3d(vertices)
    components = _empty_components(n, device)
    rhs = _empty_components(n, device)
    solutions = _empty_components(n, device)

    n_triplets = 12 * n_faces
    for _ in range(iterations):
        current = _to_vec3(positions)
        cot_entries = laplacian.cotmatrix_entries(current, faces)
        rows = wp.empty(n_triplets, dtype=wp.int32, device=device)
        cols = wp.empty(n_triplets, dtype=wp.int32, device=device)
        vals = wp.empty(n_triplets, dtype=wp.float64, device=device)
        # Generic ``cotmatrix_triplets`` casts the float32 half-cotangent weights to float64,
        # assembling the stiffness matrix natively in a single build (see issue_report.md).
        wp.launch(
            kernel_laplacian.cotmatrix_triplets,
            dim=n_faces,
            inputs=[faces, cot_entries, rows, cols, vals],
            device=device,
        )
        stiffness = wps.bsr_from_triplets(n, n, rows, cols, vals, prune_numerical_zeros=False)

        mass = laplacian.mass_matrix_entries(current, faces, dtype=wp.float64)

        # Right-hand side b = M V, formed before ``bsr_axpy`` mutates the mass matrix.
        wp.map(kernel_smoothing.extract_components, positions, out=list(components))
        for component, b in zip(components, rhs, strict=True):
            wp.map(wp.mul, mass, component, out=b)

        # A = M - lamb L (SPD: L has a negative diagonal, so subtracting it adds to the diagonal).
        system = wps.bsr_axpy(x=stiffness, y=wps.bsr_diag(diag=mass), alpha=-float(lamb), beta=1.0)
        precond = wpl.preconditioner(system, "diag")
        for b, solution, component in zip(rhs, solutions, components, strict=True):
            wp.copy(solution, component)
            wpl.cg(system, b, solution, tol=_CG_TOLERANCE, maxiter=10 * n, M=precond)
        wp.map(kernel_smoothing.combine_components, *solutions, out=positions)

    return _to_vec3(positions)


def _empty_components(
    n: int, device: wp.DeviceLike
) -> tuple[wp.array[wp.float64], wp.array[wp.float64], wp.array[wp.float64]]:
    return (
        wp.empty(n, dtype=wp.float64, device=device),
        wp.empty(n, dtype=wp.float64, device=device),
        wp.empty(n, dtype=wp.float64, device=device),
    )


def _build_implicit_system(
    operator: wps.BsrMatrix[wp.float32], lamb: float, n: int, device: wp.DeviceLike
) -> wps.BsrMatrix[wp.float64]:
    nnz = int(operator.nnz)
    n_triplets = nnz + n
    rows = wp.empty(n_triplets, dtype=wp.int32, device=device)
    cols = wp.empty(n_triplets, dtype=wp.int32, device=device)
    vals = wp.empty(n_triplets, dtype=wp.float64, device=device)
    wp.launch(
        kernel_smoothing.implicit_laplacian_triplets,
        dim=n,
        inputs=[
            operator.offsets,
            operator.columns,
            operator.values,
            wp.float64(lamb),
            wp.int32(nnz),
            rows,
            cols,
            vals,
        ],
        device=device,
    )
    return wps.bsr_from_triplets(n, n, rows, cols, vals, prune_numerical_zeros=False)


# ---------------------------------------------------------------------------
# Region smoothing solves (positionVertsSmoothly / positionVertsSmoothlySharpBd)
# ---------------------------------------------------------------------------

_CG_TOLERANCE_POSITION = 1e-10


def _mask_to_map(mask: wp.array[wp.bool]) -> tuple[wp.array[wp.int32], int]:
    """Compact index map over the ``True`` entries plus their count (exclusive scan)."""
    device = mask.device
    n = int(mask.shape[0])
    if n == 0:
        return wp.zeros(0, dtype=wp.int32, device=device), 0
    flags = wp.empty(n, dtype=wp.int32, device=device)
    wp.utils.array_cast(mask, flags)
    cmap = wp.empty(n, dtype=wp.int32, device=device)
    inclusive = wp.empty(n, dtype=wp.int32, device=device)
    wp.utils.array_scan(flags, out_array=cmap, inclusive=False)
    wp.utils.array_scan(flags, out_array=inclusive, inclusive=True)
    return cmap, int(inclusive.numpy()[-1])


def _edge_weight_matrix(
    vertices: wp.array[wp.vec3], faces: wp.array[wp.int32], edge_weights: str
) -> wps.BsrMatrix[wp.float64]:
    """Symmetric ``(n, n)`` float64 edge-weight matrix (zero diagonal); unit or clamped cotan."""
    device = vertices.device
    n = int(vertices.shape[0])
    unique_edges, inverse = tw.edges.edges_unique(faces, n_vertices=n)
    m = int(unique_edges.shape[0])
    weights = wp.zeros(m, dtype=wp.float32, device=device)
    if edge_weights == "unit":
        weights.fill_(1.0)
    elif edge_weights == "cotan":
        wp.launch(
            kernel_smoothing.edge_cotan_add,
            dim=int(faces.shape[0]) // 3,
            inputs=[vertices, faces, inverse, weights],
            device=device,
        )
        wp.map(kernel_smoothing.clamp_cotan, weights, out=weights)
    else:
        raise ValueError(f"edge_weights must be 'unit' or 'cotan', got {edge_weights!r}")
    rows = wp.empty(2 * m, dtype=wp.int32, device=device)
    cols = wp.empty(2 * m, dtype=wp.int32, device=device)
    vals = wp.empty(2 * m, dtype=wp.float64, device=device)
    wp.launch(
        kernel_smoothing.symmetric_weight_triplets,
        dim=m,
        inputs=[unique_edges, weights, rows, cols, vals],
        device=device,
    )
    return wps.bsr_from_triplets(n, n, rows, cols, vals, prune_numerical_zeros=False)


def _solve_spd_xyz(
    system: wps.BsrMatrix[wp.float64],
    rhs_x: wp.array[wp.float64],
    rhs_y: wp.array[wp.float64],
    rhs_z: wp.array[wp.float64],
    n: int,
) -> tuple[wp.array[wp.float64], wp.array[wp.float64], wp.array[wp.float64]]:
    """Solve the same SPD system for three right-hand sides (x/y/z), sharing a preconditioner."""
    device = rhs_x.device
    preconditioner = wpl.preconditioner(system, "diag")
    sol_x = wp.zeros(n, dtype=wp.float64, device=device)
    sol_y = wp.zeros(n, dtype=wp.float64, device=device)
    sol_z = wp.zeros(n, dtype=wp.float64, device=device)
    wpl.cg(system, rhs_x, sol_x, tol=_CG_TOLERANCE_POSITION, maxiter=10 * n, M=preconditioner)
    wpl.cg(system, rhs_y, sol_y, tol=_CG_TOLERANCE_POSITION, maxiter=10 * n, M=preconditioner)
    wpl.cg(system, rhs_z, sol_z, tol=_CG_TOLERANCE_POSITION, maxiter=10 * n, M=preconditioner)
    return sol_x, sol_y, sol_z


def position_verts_smoothly_sharp_boundary(
    vertices: wp.array[wp.vec3],
    faces: wp.array[wp.int32],
    free_mask: wp.array[wp.bool],
    stabilizer: float = 0.0,
) -> wp.array[wp.vec3]:
    """
    Reposition a free vertex region as the umbrella-Laplacian solution with a sharp fixed boundary.

    Ports MeshLib ``positionVertsSmoothlySharpBd``: the free vertices (``free_mask``) are moved to
    the solution of the graph-Laplacian Dirichlet system ``(D - W) x = b`` (unit edge weights),
    where the fixed one-ring neighbours are folded into ``b``, so the region rim stays sharp
    (a hard C⁰ constraint). Fixed vertices keep their positions.

    Parameters
    ----------
    vertices
        ``(n_vertices,)`` vertex positions.
    faces
        Length-``3 * n_faces`` ``wp.int32`` flat triangle index buffer.
    free_mask
        Length-``n_vertices`` ``wp.bool`` mask of the vertices to reposition.
    stabilizer
        Optional attraction to the original position (adds to the diagonal), which also makes the
        system solvable for a fully-free component. Defaults to ``0``.

    Returns
    -------
    wp.array[wp.vec3]
        New vertex positions on ``vertices.device`` (a copy; fixed vertices unchanged).

    Raises
    ------
    NotImplementedError
        On a CPU device (``warp.optim.linear.cg`` produces NaN on CPU in Warp 1.14-1.15).

    See Also
    --------
    [`position_verts_smoothly`][triwarp.smoothing.position_verts_smoothly]
    [`fill_holes_nicely`][triwarp.stitching.fill_holes_nicely]

    Notes
    -----
    The system is SPD only when no free connected component is entirely free (or ``stabilizer >
    0``); the hole-filling pipeline guarantees this because the patch rim is always fixed.
    """
    device = vertices.device
    n = int(vertices.shape[0])
    out = wp.clone(vertices)
    if int(faces.shape[0]) == 0 or n == 0:
        return out
    free_map, n_free = _mask_to_map(free_mask)
    if n_free == 0:
        return out
    _require_cuda(device, "position_verts_smoothly_sharp_boundary")

    weight_matrix = _edge_weight_matrix(vertices, faces, "unit")
    nnz = int(weight_matrix.nnz)
    size = nnz + n
    out_rows = wp.zeros(size, dtype=wp.int32, device=device)
    out_cols = wp.zeros(size, dtype=wp.int32, device=device)
    out_vals = wp.zeros(size, dtype=wp.float64, device=device)
    rhs_x = wp.zeros(n_free, dtype=wp.float64, device=device)
    rhs_y = wp.zeros(n_free, dtype=wp.float64, device=device)
    rhs_z = wp.zeros(n_free, dtype=wp.float64, device=device)
    wp.launch(
        kernel_smoothing.dirichlet_system_triplets,
        dim=n,
        inputs=[
            weight_matrix.offsets,
            weight_matrix.columns,
            weight_matrix.values,
            free_mask,
            free_map,
            vertices,
            wp.float64(stabilizer),
            out_rows,
            out_cols,
            out_vals,
            rhs_x,
            rhs_y,
            rhs_z,
        ],
        device=device,
    )
    system = wps.bsr_from_triplets(
        n_free, n_free, out_rows, out_cols, out_vals, prune_numerical_zeros=False
    )
    sol_x, sol_y, sol_z = _solve_spd_xyz(system, rhs_x, rhs_y, rhs_z, n_free)
    wp.launch(
        kernel_smoothing.scatter_free_solution,
        dim=n,
        inputs=[free_mask, free_map, sol_x, sol_y, sol_z, out],
        device=device,
    )
    return out


def position_verts_smoothly(
    vertices: wp.array[wp.vec3],
    faces: wp.array[wp.int32],
    free_mask: wp.array[wp.bool],
    edge_weights: str = "cotan",
) -> wp.array[wp.vec3]:
    """
    Reposition a free vertex region so the surface is smooth across the region boundary too.

    Ports MeshLib ``positionVertsSmoothly`` (the ``Laplacian`` least-squares solve with
    ``RememberShape::No``): every vertex in the region and its first fixed ring contributes the
    umbrella equation ``p_v = Σ_d (w_vd / ΣW) p_d``; free vertices are unknowns and fixed
    neighbours move to the right-hand side. The normal equations ``(MᵀM) x = Mᵀ b`` are solved per
    coordinate, giving a patch that is smooth (C¹) *across* the region rim, unlike the sharp-rim
    [`position_verts_smoothly_sharp_boundary`][triwarp.smoothing.position_verts_smoothly_sharp_boundary].

    Parameters
    ----------
    vertices
        ``(n_vertices,)`` vertex positions.
    faces
        Length-``3 * n_faces`` ``wp.int32`` flat triangle index buffer.
    free_mask
        Length-``n_vertices`` ``wp.bool`` mask of the vertices to reposition.
    edge_weights
        ``"cotan"`` (default, clamped cotangent weights) or ``"unit"`` (uniform).

    Returns
    -------
    wp.array[wp.vec3]
        New vertex positions on ``vertices.device`` (a copy; fixed vertices unchanged).

    Raises
    ------
    NotImplementedError
        On a CPU device.
    ValueError
        If ``edge_weights`` is not ``"cotan"`` or ``"unit"``.

    See Also
    --------
    [`position_verts_smoothly_sharp_boundary`][triwarp.smoothing.position_verts_smoothly_sharp_boundary]
    [`fill_holes_nicely`][triwarp.stitching.fill_holes_nicely]
    """
    device = vertices.device
    n = int(vertices.shape[0])
    out = wp.clone(vertices)
    if int(faces.shape[0]) == 0 or n == 0:
        return out
    free_map, n_free = _mask_to_map(free_mask)
    if n_free == 0:
        return out
    _require_cuda(device, "position_verts_smoothly")

    row_mask = tw.selection.expand_vertex_mask(faces, free_mask, 1)
    row_map, n_rows = _mask_to_map(row_mask)
    weight_matrix = _edge_weight_matrix(vertices, faces, edge_weights)
    nnz = int(weight_matrix.nnz)
    size = nnz + n
    rows = wp.zeros(size, dtype=wp.int32, device=device)
    cols = wp.zeros(size, dtype=wp.int32, device=device)
    vals = wp.zeros(size, dtype=wp.float64, device=device)
    rhs_x = wp.zeros(n_rows, dtype=wp.float64, device=device)
    rhs_y = wp.zeros(n_rows, dtype=wp.float64, device=device)
    rhs_z = wp.zeros(n_rows, dtype=wp.float64, device=device)
    wp.launch(
        kernel_smoothing.laplacian_ls_triplets,
        dim=n,
        inputs=[
            weight_matrix.offsets,
            weight_matrix.columns,
            weight_matrix.values,
            free_mask,
            row_mask,
            free_map,
            row_map,
            vertices,
            rows,
            cols,
            vals,
            rhs_x,
            rhs_y,
            rhs_z,
        ],
        device=device,
    )
    # M is (n_rows x n_free); build M and M^T from the same (swapped) triplets in a single build
    # each (never rebuilt/recast — bsr_mm determinism), then A = M^T M is SPD.
    m_matrix = wps.bsr_from_triplets(n_rows, n_free, rows, cols, vals, prune_numerical_zeros=False)
    mt_matrix = wps.bsr_from_triplets(
        n_free, n_rows, wp.clone(cols), wp.clone(rows), wp.clone(vals), prune_numerical_zeros=False
    )
    system = wps.bsr_mm(mt_matrix, m_matrix)
    atb_x = wps.bsr_mv(mt_matrix, rhs_x)
    atb_y = wps.bsr_mv(mt_matrix, rhs_y)
    atb_z = wps.bsr_mv(mt_matrix, rhs_z)
    sol_x, sol_y, sol_z = _solve_spd_xyz(system, atb_x, atb_y, atb_z, n_free)
    wp.launch(
        kernel_smoothing.scatter_free_solution,
        dim=n,
        inputs=[free_mask, free_map, sol_x, sol_y, sol_z, out],
        device=device,
    )
    return out
