"""Laplacian mesh smoothing filters (Warp)."""

from __future__ import annotations

import warp as wp
import warp.optim.linear as wpl
import warp.sparse as wps

from triwarp import laplacian
from triwarp.kernels import geodesic as kernel_geodesic
from triwarp.kernels import laplacian as kernel_laplacian
from triwarp.kernels import smoothing as kernel_smoothing
from triwarp.triangles import face_normals_and_areas
from triwarp.vertices import mean_vertex_normals

_CG_TOLERANCE = 1e-10


def _to_vec3d(vertices: wp.array[wp.vec3]) -> wp.array[wp.vec3d]:
    n = int(vertices.shape[0])
    out = wp.empty(n, dtype=wp.vec3d, device=vertices.device)
    wp.launch(kernel_smoothing.to_vec3d, dim=n, inputs=[vertices, out], device=vertices.device)
    return out


def _to_vec3(positions: wp.array[wp.vec3d]) -> wp.array[wp.vec3]:
    n = int(positions.shape[0])
    out = wp.empty(n, dtype=wp.vec3, device=positions.device)
    wp.launch(kernel_smoothing.to_vec3, dim=n, inputs=[positions, out], device=positions.device)
    return out


def _apply_operator(
    operator: wps.BsrMatrix[wp.float32],
    v_in: wp.array[wp.vec3d],
    out_lv: wp.array[wp.vec3d],
) -> None:
    wp.launch(
        kernel_laplacian.apply_operator,
        dim=int(v_in.shape[0]),
        inputs=[operator.offsets, operator.columns, operator.values, v_in, out_lv],
        device=v_in.device,
    )


def _mesh_volume(positions: wp.array[wp.vec3d], faces: wp.array[wp.int32]) -> float:
    n_faces = int(faces.shape[0]) // 3
    volumes = wp.empty(n_faces, dtype=wp.float64, device=positions.device)
    wp.launch(
        kernel_smoothing.signed_tet_volumes,
        dim=n_faces,
        inputs=[positions, faces, volumes],
        device=positions.device,
    )
    return float(volumes.numpy().sum())


def _apply_volume_constraint(
    positions: wp.array[wp.vec3d], faces: wp.array[wp.int32], vol_ini: float
) -> None:
    vol_new = _mesh_volume(positions, faces)
    if vol_new != 0.0:
        factor = (vol_ini / vol_new) ** (1.0 / 3.0)
        wp.launch(
            kernel_smoothing.scale_vertices,
            dim=int(positions.shape[0]),
            inputs=[wp.float64(factor), positions],
            device=positions.device,
        )


def _require_cuda(device: wp.DeviceLike, name: str) -> None:
    if wp.get_device(device).is_cpu:
        raise NotImplementedError(
            f"{name} requires a CUDA device: warp.optim.linear.cg produces NaN on the CPU "
            "device in Warp 1.14.0."
        )


def filter_laplacian(
    vertices: wp.array[wp.vec3],
    faces: wp.array[wp.int32],
    lamb: float = 0.5,
    iterations: int = 10,
    implicit_time_integration: bool = False,
    volume_constraint: bool = True,
    laplacian_operator: wps.BsrMatrix[wp.float32] | None = None,
) -> wp.array[wp.vec3]:
    """
    Laplacian mesh smoothing (Vollmer et al.; Desbrun et al. implicit fairing).

    Diffuses each vertex toward the mean of its 1-ring neighbors. With ``implicit_time_integration``
    the diffusion is solved implicitly (backward Euler, unconditionally stable); otherwise an
    explicit forward-Euler step is used (stable for ``lamb <= 1``). Mirrors
    [`trimesh.smoothing.filter_laplacian`][] but returns a new vertex array instead of mutating
    the mesh in place.

    Parameters
    ----------
    vertices
        ``(n_vertices,)`` mesh vertex positions.
    faces
        Length-``3 * n_faces`` ``wp.int32`` triangle index buffer.
    lamb
        Diffusion speed. ``0`` leaves the mesh unchanged; larger values smooth faster.
    iterations
        Number of smoothing passes.
    implicit_time_integration
        If ``True`` solve ``((1 + lamb) I - lamb L) V' = V`` each pass via conjugate gradient
        (**CUDA only** — raises on CPU). If ``False`` apply the explicit step
        ``V' = V + lamb (L V - V)``.
    volume_constraint
        If ``True`` rescale the mesh after each pass to preserve its initial volume, counteracting
        Laplacian shrinkage.
    laplacian_operator
        Optional precomputed row-stochastic operator (see
        [`laplacian`][triwarp.laplacian.laplacian]). Autogenerated (uniform weights) when ``None``.

    Returns
    -------
    wp.array[wp.vec3]
        Smoothed ``(n_vertices,)`` vertex positions on ``vertices.device``.

    See Also
    --------
    [`filter_taubin`][triwarp.smoothing.filter_taubin]
    [`filter_humphrey`][triwarp.smoothing.filter_humphrey]
    [`filter_implicit_fairing`][triwarp.smoothing.filter_implicit_fairing]
    [`trimesh.smoothing.filter_laplacian`][]
    """
    device = vertices.device
    n = int(vertices.shape[0])
    if n == 0 or iterations == 0:
        out = wp.empty(n, dtype=wp.vec3, device=device)
        wp.copy(out, vertices)
        return out

    operator = (
        laplacian_operator
        if laplacian_operator is not None
        else laplacian.laplacian(vertices, faces)
    )
    positions = _to_vec3d(vertices)
    vol_ini = _mesh_volume(positions, faces) if volume_constraint else 0.0

    if implicit_time_integration:
        _require_cuda(device, "filter_laplacian(implicit_time_integration=True)")
        system = _build_implicit_system(operator, lamb, n, device)
        precond = wpl.preconditioner(system, "diag")
        components = _empty_components(n, device)
        solutions = _empty_components(n, device)
        for _ in range(iterations):
            wp.launch(
                kernel_smoothing.extract_components,
                dim=n,
                inputs=[positions, *components],
                device=device,
            )
            for rhs, solution in zip(components, solutions, strict=True):
                wp.copy(solution, rhs)
                wpl.cg(system, rhs, solution, tol=_CG_TOLERANCE, maxiter=10 * n, M=precond)
            wp.launch(
                kernel_smoothing.insert_components,
                dim=n,
                inputs=[*solutions, positions],
                device=device,
            )
            if volume_constraint:
                _apply_volume_constraint(positions, faces, vol_ini)
    else:
        lv = wp.empty(n, dtype=wp.vec3d, device=device)
        nxt = wp.empty(n, dtype=wp.vec3d, device=device)
        for _ in range(iterations):
            _apply_operator(operator, positions, lv)
            wp.launch(
                kernel_smoothing.laplacian_step,
                dim=n,
                inputs=[positions, lv, wp.float64(lamb), nxt],
                device=device,
            )
            positions, nxt = nxt, positions
            if volume_constraint:
                _apply_volume_constraint(positions, faces, vol_ini)

    return _to_vec3(positions)


def filter_humphrey(
    vertices: wp.array[wp.vec3],
    faces: wp.array[wp.int32],
    alpha: float = 0.1,
    beta: float = 0.5,
    iterations: int = 10,
    laplacian_operator: wps.BsrMatrix[wp.float32] | None = None,
) -> wp.array[wp.vec3]:
    """
    Laplacian smoothing with Humphrey (HC) filtering (Vollmer et al.).

    Each pass performs a Laplacian smoothing step and then pushes the vertices partway back
    toward their original and pre-smoothing positions, strongly reducing the shrinkage of plain
    Laplacian smoothing. Mirrors [`trimesh.smoothing.filter_humphrey`][].

    Parameters
    ----------
    vertices
        ``(n_vertices,)`` mesh vertex positions.
    faces
        Length-``3 * n_faces`` ``wp.int32`` triangle index buffer.
    alpha
        Shrinkage control in ``[0, 1]``: ``0`` ignores the original positions, ``1`` disables
        smoothing.
    beta
        Correction aggressiveness in ``[0, 1]``: ``0`` disables smoothing, ``1`` is most aggressive.
    iterations
        Number of smoothing passes.
    laplacian_operator
        Optional precomputed row-stochastic operator (see
        [`laplacian`][triwarp.laplacian.laplacian]). Autogenerated (uniform weights) when ``None``.

    Returns
    -------
    wp.array[wp.vec3]
        Smoothed ``(n_vertices,)`` vertex positions on ``vertices.device``.

    See Also
    --------
    [`filter_laplacian`][triwarp.smoothing.filter_laplacian]
    [`trimesh.smoothing.filter_humphrey`][]
    """
    device = vertices.device
    n = int(vertices.shape[0])
    if n == 0 or iterations == 0:
        out = wp.empty(n, dtype=wp.vec3, device=device)
        wp.copy(out, vertices)
        return out

    operator = (
        laplacian_operator
        if laplacian_operator is not None
        else laplacian.laplacian(vertices, faces)
    )
    positions = _to_vec3d(vertices)
    original = wp.empty(n, dtype=wp.vec3d, device=device)
    wp.copy(original, positions)

    lv = wp.empty(n, dtype=wp.vec3d, device=device)
    b = wp.empty(n, dtype=wp.vec3d, device=device)
    lb = wp.empty(n, dtype=wp.vec3d, device=device)
    nxt = wp.empty(n, dtype=wp.vec3d, device=device)
    for _ in range(iterations):
        # ``positions`` doubles as the previous-iterate ``q`` (it is only read this pass).
        _apply_operator(operator, positions, lv)
        wp.launch(
            kernel_smoothing.humphrey_residual,
            dim=n,
            inputs=[lv, original, positions, wp.float64(alpha), b],
            device=device,
        )
        _apply_operator(operator, b, lb)
        wp.launch(
            kernel_smoothing.humphrey_update,
            dim=n,
            inputs=[lv, b, lb, wp.float64(beta), nxt],
            device=device,
        )
        positions, nxt = nxt, positions

    return _to_vec3(positions)


def filter_taubin(
    vertices: wp.array[wp.vec3],
    faces: wp.array[wp.int32],
    lamb: float = 0.5,
    nu: float = 0.5,
    iterations: int = 10,
    laplacian_operator: wps.BsrMatrix[wp.float32] | None = None,
) -> wp.array[wp.vec3]:
    """
    Taubin lambda/nu mesh smoothing (Vollmer et al.).

    Alternates a shrinking diffusion step (``+lamb``) on even passes with an inflating step
    (``-nu``) on odd passes, so the low-frequency shape is preserved while high-frequency noise is
    removed with little volume loss. Mirrors [`trimesh.smoothing.filter_taubin`][].

    Parameters
    ----------
    vertices
        ``(n_vertices,)`` mesh vertex positions.
    faces
        Length-``3 * n_faces`` ``wp.int32`` triangle index buffer.
    lamb
        Shrinking step size in ``[0, 1]``.
    nu
        Inflating step size in ``[0, 1]``; typically chosen so ``0 < 1/lamb - 1/nu < 0.1``.
    iterations
        Number of smoothing passes (shrink and inflate alternate by pass index).
    laplacian_operator
        Optional precomputed row-stochastic operator (see
        [`laplacian`][triwarp.laplacian.laplacian]). Autogenerated (uniform weights) when ``None``.

    Returns
    -------
    wp.array[wp.vec3]
        Smoothed ``(n_vertices,)`` vertex positions on ``vertices.device``.

    See Also
    --------
    [`filter_laplacian`][triwarp.smoothing.filter_laplacian]
    [`trimesh.smoothing.filter_taubin`][]
    """
    device = vertices.device
    n = int(vertices.shape[0])
    if n == 0 or iterations == 0:
        out = wp.empty(n, dtype=wp.vec3, device=device)
        wp.copy(out, vertices)
        return out

    operator = (
        laplacian_operator
        if laplacian_operator is not None
        else laplacian.laplacian(vertices, faces)
    )
    positions = _to_vec3d(vertices)
    lv = wp.empty(n, dtype=wp.vec3d, device=device)
    nxt = wp.empty(n, dtype=wp.vec3d, device=device)
    for index in range(iterations):
        _apply_operator(operator, positions, lv)
        coeff = lamb if index % 2 == 0 else -nu
        wp.launch(
            kernel_smoothing.laplacian_step,
            dim=n,
            inputs=[positions, lv, wp.float64(coeff), nxt],
            device=device,
        )
        positions, nxt = nxt, positions

    return _to_vec3(positions)


def filter_neighborhood_average(
    vertices: wp.array[wp.vec3],
    faces: wp.array[wp.int32],
    iterations: int = 10,
    laplacian_operator: wps.BsrMatrix[wp.float32] | None = None,
) -> wp.array[wp.vec3]:
    """
    Uniform neighborhood-average smoothing over the closed 1-ring.

    Each pass replaces every vertex by the equal-weight average of itself and its direct
    neighbors, ``v' = (v + sum(v_neighbors)) / (1 + degree)``. Unlike
    [`filter_laplacian`][triwarp.smoothing.filter_laplacian] (which averages the open 1-ring,
    excluding the vertex, and scales the result by ``lamb``) this is the simplest possible
    smoother, with no diffusion coefficient. It is the CPU/GPU-portable analogue of Open3D's
    ``TriangleMesh.filter_smooth_simple``.

    Isolated vertices (degree 0) are left unchanged.

    Parameters
    ----------
    vertices
        ``(n_vertices,)`` mesh vertex positions.
    faces
        Length-``3 * n_faces`` ``wp.int32`` triangle index buffer.
    iterations
        Number of smoothing passes.
    laplacian_operator
        Optional precomputed row-stochastic operator (see
        [`laplacian`][triwarp.laplacian.laplacian]). Autogenerated (uniform weights) when ``None``.

    Returns
    -------
    wp.array[wp.vec3]
        Smoothed ``(n_vertices,)`` vertex positions on ``vertices.device``.

    See Also
    --------
    [`filter_laplacian`][triwarp.smoothing.filter_laplacian]
    [`filter_taubin`][triwarp.smoothing.filter_taubin]
    """
    device = vertices.device
    n = int(vertices.shape[0])
    if n == 0 or iterations == 0:
        out = wp.empty(n, dtype=wp.vec3, device=device)
        wp.copy(out, vertices)
        return out

    # Symmetric adjacency (undirected 1-ring) so boundary vertices average over all their
    # neighbors, matching Open3D's ``adjacency_list``; the directed default is asymmetric there.
    operator = (
        laplacian_operator
        if laplacian_operator is not None
        else laplacian.laplacian(vertices, faces, symmetric=True)
    )
    positions = _to_vec3d(vertices)
    lv = wp.empty(n, dtype=wp.vec3d, device=device)
    nxt = wp.empty(n, dtype=wp.vec3d, device=device)
    for _ in range(iterations):
        _apply_operator(operator, positions, lv)
        wp.launch(
            kernel_smoothing.neighborhood_average_step,
            dim=n,
            inputs=[positions, lv, operator.offsets, nxt],
            device=device,
        )
        positions, nxt = nxt, positions

    return _to_vec3(positions)


def filter_mut_dif_laplacian(
    vertices: wp.array[wp.vec3],
    faces: wp.array[wp.int32],
    lamb: float = 0.5,
    iterations: int = 10,
    volume_constraint: bool = True,
    laplacian_operator: wps.BsrMatrix[wp.float32] | None = None,
) -> wp.array[wp.vec3]:
    """
    Laplacian smoothing with a mutable diffusion coefficient (Barroqueiro et al.).

    Each pass runs a Laplacian diffusion step whose speed is adapted **per vertex**: the
    coefficient ``lamber`` is scaled by how much of the vertex's Laplacian residual lies along
    its normal, so flat regions diffuse quickly while feature regions diffuse slowly. When
    ``volume_constraint`` is set, the mesh is inflated along its vertex normals (rather than
    isotropically rescaled) to counteract shrinkage. Mirrors
    [`trimesh.smoothing.filter_mut_dif_laplacian`][] but returns a new vertex array instead of
    mutating the mesh in place.

    Following the reference, the vertex normals (and the finite-difference step ``eps``) are
    computed once from the input mesh and held constant across all passes.

    Parameters
    ----------
    vertices
        ``(n_vertices,)`` mesh vertex positions.
    faces
        Length-``3 * n_faces`` ``wp.int32`` triangle index buffer.
    lamb
        Diffusion speed. ``0`` leaves the mesh unchanged; larger values smooth faster.
    iterations
        Number of smoothing passes.
    volume_constraint
        If ``True`` inflate the mesh along its vertex normals after each pass to preserve its
        initial volume (meaningful only for watertight meshes).
    laplacian_operator
        Optional precomputed row-stochastic operator (see
        [`laplacian`][triwarp.laplacian.laplacian]). Autogenerated (uniform weights) when ``None``.

    Returns
    -------
    wp.array[wp.vec3]
        Smoothed ``(n_vertices,)`` vertex positions on ``vertices.device``.

    See Also
    --------
    [`filter_laplacian`][triwarp.smoothing.filter_laplacian]
    [`filter_humphrey`][triwarp.smoothing.filter_humphrey]
    [`filter_taubin`][triwarp.smoothing.filter_taubin]
    [`trimesh.smoothing.filter_mut_dif_laplacian`][]
    """
    device = vertices.device
    n = int(vertices.shape[0])
    if n == 0 or iterations == 0:
        out = wp.empty(n, dtype=wp.vec3, device=device)
        wp.copy(out, vertices)
        return out

    operator = (
        laplacian_operator
        if laplacian_operator is not None
        else laplacian.laplacian(vertices, faces)
    )
    positions = _to_vec3d(vertices)

    # Vertex normals and eps are computed once from the input mesh and reused every pass, matching
    # the trimesh reference (which reads normals off the un-mutated mesh inside its loop).
    face_normals, areas = face_normals_and_areas(vertices, faces)
    normals = mean_vertex_normals(n, faces, face_normals)
    vol_ini = _mesh_volume(positions, faces) if volume_constraint else 0.0
    eps = 0.01 * float(areas.numpy().max()) ** 0.5 if volume_constraint else 0.0

    lv = wp.empty(n, dtype=wp.vec3d, device=device)
    adil = wp.empty(n, dtype=wp.float64, device=device)
    nxt = wp.empty(n, dtype=wp.vec3d, device=device)
    probe = wp.empty(n, dtype=wp.vec3d, device=device) if volume_constraint else None
    slope = 0.0
    for index in range(iterations):
        _apply_operator(operator, positions, lv)
        wp.launch(
            kernel_smoothing.mut_dif_adil,
            dim=n,
            inputs=[normals, positions, lv, adil],
            device=device,
        )
        mean_adil = float(adil.numpy().sum()) / n
        wp.launch(
            kernel_smoothing.mut_dif_step,
            dim=n,
            inputs=[positions, lv, adil, wp.float64(mean_adil), wp.float64(lamb), nxt],
            device=device,
        )
        positions, nxt = nxt, positions
        if volume_constraint:
            vol = _mesh_volume(positions, faces)
            if index == 0:
                wp.launch(
                    kernel_smoothing.add_scaled_normal,
                    dim=n,
                    inputs=[positions, normals, wp.float64(eps), probe],
                    device=device,
                )
                vol2 = _mesh_volume(probe, faces)
                slope = eps / (vol2 - vol) if vol2 != vol else 0.0
            wp.launch(
                kernel_smoothing.add_scaled_normal,
                dim=n,
                inputs=[positions, normals, wp.float64(slope * (vol_ini - vol)), positions],
                device=device,
            )

    return _to_vec3(positions)


def filter_implicit_fairing(
    vertices: wp.array[wp.vec3],
    faces: wp.array[wp.int32],
    lamb: float = 0.1,
    iterations: int = 10,
) -> wp.array[wp.vec3]:
    """
    Implicit fairing with the cotangent Laplace-Beltrami operator (Desbrun et al.).

    Solves the backward-Euler diffusion ``(M - lamb L) V' = M V`` each pass, where ``L`` is the
    cotangent stiffness matrix ([`cotmatrix`][triwarp.laplacian.cotmatrix]) and ``M`` the
    barycentric lumped mass matrix ([`mass_matrix`][triwarp.laplacian.mass_matrix]), both recomputed
    from the current geometry. This is the most accurate of the smoothing filters (curvature flow;
    libigl tutorial 205, MeshLib ``Laplacian`` in cotangent mode) and is **CUDA only** (raises on
    CPU). The solve uses ``float64`` throughout.

    Intended for closed (watertight) meshes. On meshes with an open boundary the unconstrained
    flow shrinks and degrades the boundary triangles; because the linear system is solved by
    conjugate gradient (the only Warp solver available), repeated passes on such meshes may
    diverge.

    Parameters
    ----------
    vertices
        ``(n_vertices,)`` mesh vertex positions.
    faces
        Length-``3 * n_faces`` ``wp.int32`` triangle index buffer.
    lamb
        Diffusion time step. Larger values smooth faster; the implicit solve is unconditionally
        stable.
    iterations
        Number of smoothing passes.

    Returns
    -------
    wp.array[wp.vec3]
        Smoothed ``(n_vertices,)`` vertex positions on ``vertices.device``.

    See Also
    --------
    [`filter_laplacian`][triwarp.smoothing.filter_laplacian]
    [`cotmatrix`][triwarp.laplacian.cotmatrix]
    [`mass_matrix`][triwarp.laplacian.mass_matrix]
    """
    device = vertices.device
    n = int(vertices.shape[0])
    n_faces = int(faces.shape[0]) // 3
    if n == 0 or n_faces == 0 or iterations == 0:
        out = wp.empty(n, dtype=wp.vec3, device=device)
        wp.copy(out, vertices)
        return out

    _require_cuda(device, "filter_implicit_fairing")
    positions = _to_vec3d(vertices)
    components = _empty_components(n, device)
    rhs = _empty_components(n, device)
    solutions = _empty_components(n, device)

    n_triplets = 12 * n_faces
    for _ in range(iterations):
        current = _to_vec3(positions)
        cot_entries = laplacian.cotmatrix_entries(current, faces)
        rows = wp.empty(n_triplets, dtype=wp.int32, device=device)
        cols = wp.empty(n_triplets, dtype=wp.int32, device=device)
        vals = wp.empty(n_triplets, dtype=wp.float64, device=device)
        wp.launch(
            kernel_geodesic.cotmatrix_triplets_f64,
            dim=n_faces,
            inputs=[faces, cot_entries, rows, cols, vals],
            device=device,
        )
        stiffness = wps.bsr_from_triplets(n, n, rows, cols, vals, prune_numerical_zeros=False)

        mass = wp.empty(n, dtype=wp.float64, device=device)
        wp.utils.array_cast(laplacian.mass_matrix_entries(current, faces), mass)

        # Right-hand side b = M V, formed before ``bsr_axpy`` mutates the mass matrix.
        wp.launch(
            kernel_smoothing.extract_components,
            dim=n,
            inputs=[positions, *components],
            device=device,
        )
        for component, b in zip(components, rhs, strict=True):
            wp.launch(
                kernel_smoothing.scale_by_diagonal,
                dim=n,
                inputs=[mass, component, b],
                device=device,
            )

        # A = M - lamb L (SPD: L has a negative diagonal, so subtracting it adds to the diagonal).
        system = wps.bsr_axpy(x=stiffness, y=wps.bsr_diag(diag=mass), alpha=-float(lamb), beta=1.0)
        precond = wpl.preconditioner(system, "diag")
        for b, solution, component in zip(rhs, solutions, components, strict=True):
            wp.copy(solution, component)
            wpl.cg(system, b, solution, tol=_CG_TOLERANCE, maxiter=10 * n, M=precond)
        wp.launch(
            kernel_smoothing.insert_components,
            dim=n,
            inputs=[*solutions, positions],
            device=device,
        )

    return _to_vec3(positions)


def _empty_components(
    n: int, device: wp.DeviceLike
) -> tuple[wp.array[wp.float64], wp.array[wp.float64], wp.array[wp.float64]]:
    return (
        wp.empty(n, dtype=wp.float64, device=device),
        wp.empty(n, dtype=wp.float64, device=device),
        wp.empty(n, dtype=wp.float64, device=device),
    )


def _build_implicit_system(
    operator: wps.BsrMatrix[wp.float32], lamb: float, n: int, device: wp.DeviceLike
) -> wps.BsrMatrix[wp.float64]:
    nnz = int(operator.nnz)
    n_triplets = nnz + n
    rows = wp.empty(n_triplets, dtype=wp.int32, device=device)
    cols = wp.empty(n_triplets, dtype=wp.int32, device=device)
    vals = wp.empty(n_triplets, dtype=wp.float64, device=device)
    wp.launch(
        kernel_smoothing.implicit_laplacian_triplets,
        dim=n,
        inputs=[
            operator.offsets,
            operator.columns,
            operator.values,
            wp.float64(lamb),
            wp.int32(nnz),
            rows,
            cols,
            vals,
        ],
        device=device,
    )
    return wps.bsr_from_triplets(n, n, rows, cols, vals, prune_numerical_zeros=False)
